#!/bin/bash

# Get all arguments passed to the script
ARGS="$@"

# Get the directory where the script is located to reference mvnw correctly
DP0=$(dirname "$0")

# Execute Maven wrapper
# We use "$DP0/mvnw" to ensure we call the wrapper in the script's directory
"$DP0/mvnw" -f "$DP0/pom.xml" compile \
    exec:exec -Dexec.executable="java" \
    -Dexec.args="-cp target/classes:%%classpath com.nkutsche.issues.SaxonCaller"